<a href="https://colab.research.google.com/github/VaishnaviJB/demo/blob/main/vaishnavi_JB_(2575345)_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.create a 3x3x3 array with random values

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.69990312 0.14361475 0.35707323]
  [0.10208965 0.60985869 0.16254031]
  [0.56429888 0.01292979 0.44486186]]

 [[0.19586244 0.07518663 0.70435494]
  [0.6228839  0.24741148 0.53508564]
  [0.0608582  0.22465866 0.27090324]]

 [[0.77231272 0.31648302 0.34991991]
  [0.88453796 0.15168492 0.04175655]
  [0.0106841  0.19747905 0.23516638]]]


2.create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set values 1, 2, 3, 4 just below the diagonal
values = [1, 2, 3, 4]
for i in range(1, 5):
    matrix[i, i - 1] = values[i - 1]

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


3.create a 8x8 matrix and fill it with a checker board pattern

In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

# Use slicing to set alternate rows and columns to 1
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


5. How to find common value between two arrays

In [18]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)

Common values: [3 4 5]


4.normalize a 5x5  random matrix

In [5]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate mean and standard deviation
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.51770029 0.56695462 0.46644187 0.90757998 0.95963194]
 [0.09043837 0.7015235  0.04717852 0.03784496 0.88598812]
 [0.88801907 0.8875438  0.73191157 0.50502766 0.43582207]
 [0.33093624 0.29532217 0.3094904  0.25336692 0.9882433 ]
 [0.62476204 0.16330517 0.72403722 0.66452369 0.40992307]]

Normalized Matrix:
[[-0.06215199  0.10753713 -0.23874556  1.28104654  1.46037397]
 [-1.53413838  0.57114868 -1.68317555 -1.71533118  1.2066591 ]
 [ 1.21365604  1.21201868  0.67584049 -0.10581124 -0.34423569]
 [-0.70558432 -0.82828056 -0.77946873 -0.9728232   1.55894474]
 [ 0.30669304 -1.28310048  0.64871207  0.44367833 -0.43346195]]


6. How to get the dates of yesterday, today, tomorrow.

In [6]:
import numpy as np
from datetime import datetime, timedelta

# Get the current date (today)
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Create NumPy arrays for the dates
dates = np.array([yesterday, today, tomorrow])

# Format the dates as strings if needed
date_strings = [date.strftime("%Y-%m-%d") for date in dates]

print("Yesterday:", date_strings[0])
print("Today:", date_strings[1])
print("Tomorrow:", date_strings[2])

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


7.consider two random array A and B check if they are equal

In [7]:
import numpy as np

# Generate two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the arrays are equal
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


8.create a random vector of size 10 and replace the maximum value by 0

In [8]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector:")
print(random_vector)

Random Vector:
[0.37506029 0.76343289 0.42726803 0.86534782 0.21652665 0.23916497
 0.52473281 0.03329173 0.16459014 0.        ]


9. How to print all the values of an array.

In [9]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Iterate through the array and print each value
for value in my_array:
    print(value)

1
2
3
4
5


10.subtract the mean of each row of a matrix

In [10]:
import numpy as np

# Create a sample matrix (you can replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix using broadcasting
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


11.consider a given vector how to add 1 to each element indexed by a second vector(be careful with repeated indices)?

In [11]:
import numpy as np

# Given vector
given_vector = np.array([10, 20, 30, 40, 50])

# Second vector with indices
indices_to_add_1 = np.array([1, 2, 3, 3, 4])

# Find unique indices and their counts
unique_indices, counts = np.unique(indices_to_add_1, return_counts=True)

# Add 1 to each element at the unique indices
given_vector[unique_indices] += counts

print("Given Vector:")
print(given_vector)

Given Vector:
[10 21 31 42 51]


12. How to get a diagonal of dot product?

In [12]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Extract the diagonal elements using np.diag
diagonal_elements = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal Elements:")
print(diagonal_elements)

Dot Product:
[[19 22]
 [43 50]]

Diagonal Elements:
[19 50]


13.How to find the most frequent value in an array?

In [13]:
import numpy as np

# Create a NumPy array (you can replace this with your own array)
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])

# Find the most frequent value
most_frequent_value = np.bincount(arr).argmax()

print("Most frequent value:", most_frequent_value)

Most frequent value: 4


14.How to get the n largest values of an array

In [14]:
import numpy as np

# Create a NumPy array (you can replace this with your own array)
arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

# Get the n largest values (e.g., n=3)
n = 3
n_largest_values = np.partition(arr, -n)[-n:]

print("N largest values:", n_largest_values)

N largest values: [7 8 9]


15.How to create a record array from a regular array?

In [16]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 22)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# 'ID', 'Name', and 'Age' are the field names, and their data types are specified.

# Accessing data in the record array
print("ID:", regular_array['ID'])
print("Name:", regular_array['Name'])
print("Age:", regular_array['Age'])

ID: [1 2 3]
Name: ['Alice' 'Bob' 'Charlie']
Age: [25 30 22]


16. How to swap two rows of an array?

In [15]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Swap rows (for example, swapping row 0 and row 1)
my_array[0, :], my_array[1, :] = my_array[1, :], my_array[0, :]

# Print the modified array
print(my_array)

[[4 5 6]
 [4 5 6]
 [7 8 9]]


17.write python code to reshape to the next dimension of numpy array?

In [17]:
import numpy as np

# Create the original NumPy array
x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])

# Reshape to the next dimension (1x9)
reshaped_array = x.reshape(1, -1)

# Print the reshaped array
print(reshaped_array)

[[ 23  34 121  23  22  67 686 434 123]]
